version: '3'
services:
  redisnode01:
    image: redis
    ports:
      - "6379:6379"
  nodejsserver01:
    depends_on:
      - "redisnode01"
    image: my-nodejs
    ports: 
      - "8081:8081"
  haproxyserver:
    depends_on:
      - "nodejsserver01"
    image: my-haproxy
    ports: 
      - "90:80"
